version: '3'

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - frappe_net

  redis:
    image: redis:latest
    networks:
      - frappe_net

  frappe:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SITE_NAME: ${SITE_NAME:-test_site}
      SITES_PATH: .bench/sites
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      DB_ROOT_PASSWORD: root
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_ROOT_USER: root
    volumes:
      - sites_volume:/home/frappe/frappe-bench/sites
    networks:
      - frappe_net

volumes:
  mariadb:
  redis:
  sites_volume:

networks:
  frappe_net:
