doctype:
  - name: Service Report
    fields:
      - fieldname: service_request
        fieldtype: Link
        options: Service Request
      - fieldname: report_date
        fieldtype: Date
      - fieldname: assigned_engineers
        fieldtype: Table
        options: Assigned Engineer Item
    events:
      validate: ferum_customs.custom_logic.service_report_hooks.validate
      on_submit: ferum_customs.custom_logic.service_report_hooks.on_submit
      after_insert: ferum_customs.custom_logic.service_report_hooks.after_insert
      on_cancel: ferum_customs.custom_logic.service_report_hooks.on_cancel

  - name: Service Request
    events:
      validate: ferum_customs.custom_logic.service_request_hooks.validate
      on_update_after_submit: ferum_customs.custom_logic.service_request_hooks.on_update_after_submit
      on_trash: ferum_customs.custom_logic.service_request_hooks.prevent_deletion_with_links
      after_insert: ferum_customs.custom_logic.service_request_hooks.after_insert
      on_cancel: ferum_customs.custom_logic.service_request_hooks.on_cancel

  - name: Service Object
    events:
      validate: ferum_customs.custom_logic.service_object_hooks.validate

  - name: Payroll Entry Custom
    events:
      validate: ferum_customs.custom_logic.payroll_entry_hooks.validate
      before_save: ferum_customs.custom_logic.payroll_entry_hooks.before_save

  - name: Custom Attachment
    events:
      on_trash: ferum_customs.custom_logic.file_attachment_utils.on_custom_attachment_trash

  - name: Service Contract
    fields:
      - fieldname: customer
        fieldtype: Link
        options: Customer
      - fieldname: sla
        fieldtype: Int
    events: {}

  - name: Invoice
    fields:
      - fieldname: service_report
        fieldtype: Link
        options: Service Report
    events: {}

  - name: Site
    fields:
      - fieldname: address
        fieldtype: Data
    events: {}

  - name: Maintenance Plan
    fields:
      - fieldname: site
        fieldtype: Link
        options: Site
    events: {}
