name: CI

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      CI: "true"                # позволяет bench работать под root в GitHub runner
      MYSQL_ROOT_PASSWORD: "root"
      ADMIN_PASSWORD: "admin"
    steps:
      # --- Checkout --------------------------------------------------------
      - uses: actions/checkout@v4

      # --- Python ----------------------------------------------------------
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"    # P0‑1c: обязательный параметр

      # --- Cache -----------------------------------------------------------
      - name: Cache pip & bench
        uses: actions/cache@v4       # P0‑1b: параметризуем
        with:
          path: |
            ~/.cache/pip
            ~/.bench
          key: ${{ runner.os }}-pip-bench-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-bench-

      # --- System dependencies --------------------------------------------
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential python3-dev libffi-dev libmysqlclient-dev \
               mariadb-server redis-server xvfb libfontconfig wkhtmltopdf
          # Node 20 + yarn 1.x for Frappe v15
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g yarn@1.22

      # --- Python dependencies --------------------------------------------
      - name: Install Python deps
        run: |
          pip install --no-cache-dir -r requirements-dev.txt  # содержит frappe + erpnext
          pip install --no-cache-dir frappe-bench

      # --- Bench init & site ----------------------------------------------
      - name: Init bench & test_site
        run: |
          bench init frappe-bench --frappe-branch version-15
          cd frappe-bench
          bench new-site test_site \
                --admin-password "$ADMIN_PASSWORD" \
                --mariadb-root-password "$MYSQL_ROOT_PASSWORD" \
                --no-mariadb-socket
          bench get-app erpnext --branch version-15
          bench --site test_site install-app erpnext
          bench set-config allow_tests true

      # --- Tests -----------------------------------------------------------
      - name: Run pytest
        run: |
          cd frappe-bench
          pytest --maxfail=1 -q

      # --- Artifacts -------------------------------------------------------
      - name: Upload pytest cache
        if: failure() || success()
        uses: actions/upload-artifact@v4  # P0‑1a: v4 artefact action
        with:
          name: junit-report
          path: frappe-bench/.pytest_cache/v
