name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SITE_NAME: test_site
      SITES_PATH: .bench/sites
      ADMIN_PASSWORD: admin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r dev-requirements.txt
      - name: Prepare Frappe test site
        run: |
          bash scripts/setup_test_site.sh
        env:
          SITE_NAME: ${{ env.SITE_NAME }}
          SITES_PATH: ${{ env.SITES_PATH }}
          ADMIN_PASSWORD: ${{ env.ADMIN_PASSWORD }}
      - name: Run pytest
        run: pytest -q
